base_dir: .
batch_around_ped: 128
batch_size: 32
clip: 1
config: ./savedata/1/sralstmm//config_test.yaml
dataset: eth5
dropratio: 0.5
gpu: 0
ifdebug: false
ifdropout: true
ifsave_results: false
ifshow_detail: true
ifvalid: true
input_embed_size: 32
input_size: 2
learning_rate: 0.0015
load_model: 199
model: models.SRA_LSTM_M
model_dir: ./savedata/1/sralstmm/
neighbor_thred: 2
noise_dim: 16
num_epochs: 300
obs_length: 8
output_size: 2
phase: test
pred_length: 12
pretrain_load: 0
pretrain_model: sralstmm
randomRotate: true
rela_ac: relu
rela_dropratio: 0.5
rela_embed_size: 32
rela_hidden_size: 64
rela_input: 2
rnn_size: 64
sample_num: 20
save_base_dir: ./savedata/
save_dir: ./savedata/1/
seq_length: 16
show_step: 100
social_tensor_size: 64
start_test: -1
std_in: 0.2
std_out: 0.1
test_batch_size: 16
test_set: 1
train_model: sralstmm
using_cuda: true
val_batch_size: 32
val_fraction: 0.0
